const db = require('./connection');
const { User } = require('../models');
const bcrypt = require('bcrypt');

db.once('open', async () => {
    await User.deleteMany();
    await User.insertMany([
        {
           username: 'harryisawesome',
           firstname: 'Hary',
           email: 'harry@harry.com',
           password: 'password',
           age: 27,
           location: 'CT',
           gender: 'Male',
           preference: ['Female'],
           agerangemin: 25,
           agerangemax: 30,
           aboutme: 'I like being a solo artist, but if I meet the right person, I would be a part of a group again!',
           img: 'https://vaccidate-images2.s3.amazonaws.com/27yearOldMale.jpeg'
        },
        {
            username: 'coolgirl',
            firstname: 'chelsea',
            email: 'chelsea@chelsea.com',
            password: 'password',
            age: 22,
            location: 'CT',
            gender: 'Female',
            preference: ['Male', 'Female'],
            agerangemin: 24,
            agerangemax: 28,
            aboutme: 'I love Chelsea FC. There is something about winter and sitting by a fire with a drink in my hand that lets me know this life is worth living.',
            img: 'https://vaccidate-images2.s3.amazonaws.com/22yearoldwoman.jpeg'
         },
         {
            username: 'singlemale1',
            firstname: 'Hank',
            email: 'Hank@Hank.com',
            password: 'password',
            age: 55,
            location: 'CT',
            gender: 'Male',
            preference:['Female'],
            agerangemin: 50,
            agerangemax: 56,
            aboutme: 'Propane and propane accessories what everyone wants. I do not have an anger problem, I have an idiot problem!',
            img: 'https://vaccidate-images2.s3.amazonaws.com/55yearoldmale.jpeg'
         },
         {
            username: 'singlfemale1',
            firstname: 'Patti',
            email: 'Patti@Patti.com',
            password: 'password',
            age: 34,
            location: 'CT',
            gender: 'Female',
            preference: ['Female', 'Male', 'Non-binary'],
            agerangemin: 30,
            agerangemax: 40,
            aboutme: 'I like to sit around and read a good book and talk, but sometimes I like to go and play laser tag.', 
            img: 'https://vaccidate-images2.s3.amazonaws.com/34yearoldwoman.jpeg'
         },
         {
            username: 'singlenonbi1',
            firstname: 'Franklin',
            email: 'Franklin@Franklin.com',
            password: 'password',
            age: 29,
            location: 'CT',
            gender: 'Non-binary',
            preference: ['Male', 'Female', 'Non-binary'],
            agerangemin: 30,
            agerangemax: 40,
            aboutme: 'Sometimes it takes a while for me to come out of my shell, but when I do, its all fun and memories to make.',
            img: 'https://vaccidate-images2.s3.amazonaws.com/29yearoldmale.jpeg'
         },
         {
            username: 'singlemale2',
            firstname: 'Xavier',
            email: 'Xavier@Xavier.com',
            password: 'password',
            age: 45,
            location: 'CT',
            gender: 'Male',
            preference: ['Female', 'Male'],
            agerangemin: 30,
            agerangemax: 47,
            aboutme: 'There are only a few things that can get me excited. Getting to know you and wondering when our next date is going to be.',
            img: 'https://vaccidate-images2.s3.amazonaws.com/45yearoldmale.jpeg'
         },
         {
            username: 'singlefemale2',
            firstname: 'Karen',
            email: 'Karen@Karen.com',
            password: 'password',
            age: 58,
            location: 'CT',
            gender: 'Female',
            preference: ['Male', 'Female'],
            agerangemin: 30,
            agerangemax: 47,
            aboutme: 'I will not want to speak to the manger when I am around you. I believe in natural remedies to solve all problems. Except COVID. GET VACCINATED!',
            img: 'https://vaccidate-images2.s3.amazonaws.com/58yearoldwoman.jpeg'
         },
         {
            username: 'singlemale3',
            firstname: 'Dude',
            email: 'Dude@Dude.com',
            password: 'password',
            age: 38,
            location: 'CT',
            gender: 'Male',
            preference: ['Non-binary'],
            agerangemin: 30,
            agerangemax: 47,
            aboutme: 'Man, hanging by the beach is the best. Surfing and skating are awesome. Let us all just chill a little and just relax man.',
            img: 'https://vaccidate-images2.s3.amazonaws.com/38yearoldmale.jpeg'
         },
         {
            username: 'singlemale4',
            firstname: 'George',
            email: 'George@gmail.com',
            password: 'password',
            age: '60',
            location: 'CT',
            gender: 'Male',
            preference: ['Female'],
            agerangemin: 18,
            agerangemax: 65,
            aboutme: 'I have had many different roles in life, the best one would be to be your partner!',
            img: 'https://vaccidate-images2.s3.amazonaws.com/georgeClooney.jpeg'
         },
         {
            username: 'leslieknope',
            firstname: 'Leslie',
            email: 'pawnee@gmail.com',
            password: 'password',
            age: 38,
            location: 'CT',
            gender: 'Female',
            preference: ['Male'],
            agerangemin: 18,
            agerangemax: 50,
            aboutme: 'If we go on a date, we can either go to the park, or go to Paunch Burger and get the 512 oz soda!',
            img: 'https://vaccidate-images2.s3.amazonaws.com/LeslieKnope.jpeg'
         },
         {
            username: 'ronswanson',
            firstname: 'Ron',
            email: 'ron@gmail.com',
            password: 'password',
            age: 54,
            location: 'CT',
            gender: 'Male',
            preference: ['Female'],
            agerangemin: 30,
            agerangemax: 50,
            aboutme: 'There is only one thing I hate more than lying: skim milk. Which is water that is lying about being milk',
            img: 'https://vaccidate-images2.s3.amazonaws.com/RonSwanson.jpeg'
         },
         {
            username: 'jessepinkman',
            firstname: 'Jesse',
            email: 'jesse@gmail.com',
            password: 'password',
            age: 24,
            location: 'CT',
            gender: 'Male',
            preference: ['Female'],
            agerangemin: 18,
            agerangemax: 50,
            aboutme: 'Yeah science Bitch! Science is okay but slinging crystal is what I used to do. I wanted to move to Alaska but I came here for a reason, and I think that reason is you!',
            img: 'https://vaccidate-images2.s3.amazonaws.com/jessepinkman.jpeg'
         },
         {
            username: 'hermoniegranger',
            firstname: 'Hermonie',
            email: 'hermonie@gmail.com',
            password: 'password',
            age: 29,
            location: 'CT',
            gender: 'Female',
            preference: ['Male'],
            agerangemin: 18,
            agerangemax: 50,
            aboutme: 'Ron was the best and I will always love him, but as a friend. can you allow me to alohomora your heart?',
            img: 'https://vaccidate-images2.s3.amazonaws.com/hermoniegranger.jpeg'
         },
         {
            username: 'rosadiaz',
            firstname: 'Rosa',
            email: 'rosa@gmail.com',
            password: 'password',
            age: 35,
            location: 'CT',
            gender: 'Female',
            preference: ['Male', 'Female', 'Non-binary'],
            agerangemin: 25,
            agerangemax: 60,
            aboutme: 'Private Investigator. That is all I will share here',
            img: 'https://vaccidate-images2.s3.amazonaws.com/rosadiaz.jpeg'
         },
         {
            username: 'Cersei',
            firstname: 'Cersei',
            email: 'Cersei@gmail.com',
            password: 'password',
            age: 42,
            location: 'CT',
            gender: 'Female',
            preference: ['Male'],
            agerangemin: 35,
            agerangemax: 55,
            aboutme: 'When you play the game of thrones, you win or you die.',
            img: 'https://vaccidate-images2.s3.amazonaws.com/CerseiLannister.jpeg'
         },
         {
            username: 'rossgeller',
            firstname: 'Ross',
            email: 'ross@gmail.com',
            password: 'password',
            age: 48,
            location: 'CT',
            gender: 'Male',
            preference: ['Female'],
            agerangemin: 35,
            agerangemax: 80,
            aboutme: 'I would not be on a break with you. I like fossils and dinosaurs!',
            img: 'https://vaccidate-images2.s3.amazonaws.com/RossGeller.jpeg'
         },
         {
            username: 'macphilly',
            firstname: 'Mac',
            email: 'mac@gmail.com',
            password: 'password',
            age: 46,
            location: 'CT',
            gender: 'Male',
            preference: ['Male'],
            agerangemin: 24,
            agerangemax: 67,
            aboutme: 'I am playing both sides, so I always come out on top. I would also like to be on top of you.',
            img: 'https://vaccidate-images2.s3.amazonaws.com/macsunny.jpeg'
         },
         {
            username: 'oliviabensen',
            firstname: 'Olivia',
            email: 'olivia@gmail.com',
            password: 'password',
            age: 52,
            location: 'CT',
            gender: 'Female',
            preference: ['Male'],
            agerangemin: 40,
            agerangemax: 74,
            aboutme: 'The only crime scene that you will see is your bedroom after a date with me!',
            img: 'https://vaccidate-images2.s3.amazonaws.com/Oliviabenson.jpeg'
         },
         {
            username: 'jacksparrow',
            firstname: 'Jack',
            email: 'jacksparrow@gmail.com',
            password: 'password',
            age: 46,
            location: 'CT',
            gender: 'Male',
            preference: ['Male', 'Female', 'Non-binary'],
            agerangemin: 18,
            agerangemax: 35,
            aboutme: 'My compass is pointing me to your heart, will you allow me to find that buried treasure?',
            img: 'https://vaccidate-images2.s3.amazonaws.com/Captain_Jack_Sparrow.jpeg'
         },
         {
            username: 'batman',
            firstname: 'Bruce',
            email: 'batman1@gmail.com',
            password: 'password',
            age: 39,
            location: 'CT',
            gender: 'Male',
            preference: ['Female'],
            agerangemin: 27,
            agerangemax: 55,
            aboutme: 'I moved from Gotham City to get away from it all. I work at night so we have to go on dates during the day.',
            img: 'https://vaccidate-images2.s3.amazonaws.com/brucebatman.jpeg'
         },
         {
            username: 'hanshotfirst',
            firstname: 'Han',
            email: 'han@gmail.com',
            password: 'password',
            age: 68,
            location: 'CT',
            gender: 'Male',
            preference: ['Female', 'Non-binary'],
            agerangemin: 28,
            agerangemax: 59,
            aboutme: 'I can feel a force between us. The other guys shot first. I know something we can do in less than 12 parsecs',
            img: 'https://vaccidate-images2.s3.amazonaws.com/hansolo.jpeg'
         },
         {
            username: 'jamesbond',
            firstname: 'James',
            email: 'james@gmail.com',
            password: 'password',
            age: 43,
            location: 'CT',
            gender: 'Male',
            preference: ['Female'],
            agerangemin: 28,
            agerangemax: 80,
            aboutme: 'A Martini. Shaken, Not Stirred. I have been with so many women I want to settle down with the right one.',
            img: 'https://vaccidate-images2.s3.amazonaws.com/jamesbond.jpeg'
         },
         {
            username: 'austinpowers',
            firstname: 'Austin',
            email: 'austinpowers@gmail.com',
            password: 'password',
            age: 36,
            location: 'CT',
            gender: 'Male',
            preference: ['Male', 'Female', 'Non-binary'],
            agerangemin: 18,
            agerangemax: 90,
            aboutme: 'International Man of Mystery. So, Shall We Shag Now, Or Shall We Shag Later? ',
            img: 'https://vaccidate-images2.s3.amazonaws.com/austinpowers.jpeg'
         },
         {
            username: 'willowrosenberg',
            firstname: 'Willow',
            email: 'willowrosenberg@gmail.com',
            password: 'password',
            age: 36,
            location: 'CT',
            gender: 'Female',
            preference: ['Female', 'Non-binary'],
            agerangemin: 20,
            agerangemax: 69,
            aboutme: 'If You Hurt Her, I Will Beat You To Death With A Shovel',
            img: 'https://vaccidate-images2.s3.amazonaws.com/willoerosenburg.jpeg'
         },
         {
            username: 'myprecious',
            firstname: 'Smeagol',
            email: 'Smeagol@gmail.com',
            password: 'password',
            age: 68,
            location: 'CT',
            gender: 'Male',
            preference: ['Male', 'Female', 'Non-binary'],
            agerangemin: 30,
            agerangemax: 69,
            aboutme: 'I am here to find my precious! MY PRECIOUS!!',
            img: 'https://vaccidate-images2.s3.amazonaws.com/gollum.jpeg'
         }

    ])
    console.log('Users seeded!');
    process.exit();
});